name: HoYoverse Codes Scrape

on:
  schedule:
    - cron: '0 8,16 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute Genshin Code check
        run: python scrape.py --game genshin --webhook ${{ secrets.GENSHIN_DISCORD_WEBHOOK }}

      - name: execute Honkai Code check
        run: python scrape.py --game honkai --webhook ${{ secrets.HONKAI_DISCORD_WEBHOOK }}

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "[Data Scrapers] Refreshed data from Fandom" --allow-empty)

      - name: push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
